CREATE DATABASE AG_TEST
GO

USE AG_TEST
GO

CREATE TABLE CLIENT (
    CODE INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME NVARCHAR(100) NOT NULL,
    LAST_NAME NVARCHAR(100) NOT NULL,
    CONTACT_NUMBER NVARCHAR(20) NOT NULL,
    OCCUPATION NVARCHAR(100)
);
GO

CREATE TABLE CARD (
    CARD_ID INT IDENTITY(1,1) PRIMARY KEY,
    CLIENT_ID INT NOT NULL,
    CARD_TYPE TINYINT NOT NULL CHECK (CARD_TYPE IN (1, 2)),
    BANK NVARCHAR(100) NOT NULL,
    CARD_NUMBER NVARCHAR(20) NOT NULL,
    EXPIRY_MONTH TINYINT NOT NULL,
    EXPIRY_YEAR INT NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CODE) ON DELETE CASCADE
);
GO

ALTER TABLE Card
ADD CONSTRAINT UQ_CARD_CLIENT UNIQUE (CARD_ID, CLIENT_ID);